In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("construction_data.csv")

In [3]:
df.head()

,area,material_quality,location_factor,labor_cost,project_type,floors,soil_type,weather_index,material_price_index,contractor_experience,equipment_availability,project_complexity,permits_delay,transport_cost,inflation_factor,cost,time
0,2048,1,1.336727,71963,2,3,1,0.580171,1.520131,12,0.648664,3,27,17892,1.089126,922624,323
1,1730,2,1.636643,90401,2,8,1,0.499778,1.463073,14,0.927116,1,0,10517,1.009000,984896,272
2,2123,1,1.923715,92116,1,8,1,0.767765,1.361045,3,0.702000,1,13,18631,1.050133,801122,378
3,2561,2,1.364496,128736,2,1,1,0.571060,1.308105,2,0.603990,1,26,25950,1.086693,1845967,281
4,1682,1,1.273239,82584,1,8,1,0.486288,0.992247,4,0.544938,1,0,10597,0.998237,461075,266

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   area                    100000 non-null  int64
 1   material_quality        100000 non-null  int64
 2   location_factor         100000 non-null  float64
 3   labor_cost              100000 non-null  int64
 4   project_type            100000 non-null  int64
 5   floors                  100000 non-null  int64
 6   soil_type               100000 non-null  int64
 7   weather_index           100000 non-null  float64
 8   material_price_index    100000 non-null  float64
 9   contractor_experience   100000 non-null  int64
 10  equipment_availability  100000 non-null  float64
 11  project_complexity      100000 non-null  int64
 12  permits_delay           100000 non-null  int64
 13  transport_cost          100000 non-null  int64
 14  inflation_factor        100000 non-null  float64
 15  cost                    100000 non-null  int64
 16  time                    100000 non-null  int64
dtypes: float64(5), int64(12)
memory usage: 13.0 MB

In [5]:
df["cost_per_sqft_est"] = df["material_price_index"] * df["material_quality"]

In [6]:
df["labor_intensity"] = df["labor_cost"] / df["area"]

In [7]:
df["risk_index"] = (df["weather_index"] +(df["soil_type"] / 3) +(df["project_complexity"] / 3))

In [8]:
df["efficiency"] = (df["contractor_experience"] *df["equipment_availability"])

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   area                    100000 non-null  int64
 1   material_quality        100000 non-null  int64
 2   location_factor         100000 non-null  float64
 3   labor_cost              100000 non-null  int64
 4   project_type            100000 non-null  int64
 5   floors                  100000 non-null  int64
 6   soil_type               100000 non-null  int64
 7   weather_index           100000 non-null  float64
 8   material_price_index    100000 non-null  float64
 9   contractor_experience   100000 non-null  int64
 10  equipment_availability  100000 non-null  float64
 11  project_complexity      100000 non-null  int64
 12  permits_delay           100000 non-null  int64
 13  transport_cost          100000 non-null  int64
 14  inflation_factor        100000 non-null  float64
 15  cost                    100000 non-null  int64
 16  time                    100000 non-null  int64
 17  cost_per_sqft_est       100000 non-null  float64
 18  labor_intensity         100000 non-null  float64
 19  risk_index              100000 non-null  float64
 20  efficiency              100000 non-null  float64
dtypes: float64(9), int64(12)
memory usage: 16.0 MB

In [10]:
df.to_csv("data.csv")

In [11]:
df.describe()

,area,material_quality,location_factor,labor_cost,project_type,floors,soil_type,weather_index,material_price_index,contractor_experience,...,project_complexity,permits_delay,transport_cost,inflation_factor,cost,time,cost_per_sqft_est,labor_intensity,risk_index,efficiency
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.00000,100000.000000,100000.000000,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,1800.717110,1.803970,1.401786,81051.000240,1.702160,5.508390,1.699460,0.499924,1.300429,7.505650,...,1.69648,14.507150,18005.155910,1.049959,1.114036e+06,277.142850,2.346232,45.006646,1.631904,5.628116
std,498.322826,0.749205,0.293888,27661.836242,0.780934,2.873307,0.779706,0.173422,0.199382,4.043418,...,0.78086,8.669351,7310.482971,0.050217,5.895310e+05,69.401179,1.049797,8.660076,0.406524,3.274606
min,500.000000,1.000000,0.800000,15014.000000,1.000000,1.000000,1.000000,0.200004,0.800000,1.000000,...,1.00000,0.000000,2518.000000,0.817779,1.126640e+05,67.000000,0.800000,30.002335,0.866702,0.500022
25%,1462.000000,1.000000,1.197114,61154.000000,1.000000,3.000000,1.000000,0.349724,1.164893,4.000000,...,1.00000,7.000000,12437.750000,1.016106,6.674625e+05,227.000000,1.363798,37.531894,1.320159,2.861103
50%,1801.000000,2.000000,1.399242,78581.500000,2.000000,6.000000,2.000000,0.499970,1.299698,8.000000,...,1.00000,14.000000,17045.000000,1.050025,9.809320e+05,273.000000,2.335342,45.023080,1.616148,5.424343
75%,2138.000000,2.000000,1.601776,98697.750000,2.000000,8.000000,2.000000,0.650378,1.435355,11.000000,...,2.00000,22.000000,22734.000000,1.083697,1.443472e+06,323.000000,3.008190,52.496417,1.921705,7.971815
max,4039.000000,3.000000,2.500000,212381.000000,3.000000,10.000000,3.000000,0.799992,2.000000,14.000000,...,3.00000,29.000000,55298.000000,1.250324,5.239059e+06,585.000000,6.000000,60.045808,2.799905,13.999781

In [12]:
df.isnull().sum()

area                      0
material_quality          0
location_factor           0
labor_cost                0
project_type              0
floors                    0
soil_type                 0
weather_index             0
material_price_index      0
contractor_experience     0
equipment_availability    0
project_complexity        0
permits_delay             0
transport_cost            0
inflation_factor          0
cost                      0
time                      0
cost_per_sqft_est         0
labor_intensity           0
risk_index                0
efficiency                0
dtype: int64